a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
c = int(input("Enter the third number : "))
output = (a & b) | ((b | c) & (b & c))
print("Output of circuit is :",output)